apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
spec:
  source:
    repoURL: https://github.com/xxx/your-gitops-repo.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
